### ISSUE TITLE
new release and prebuilt binaries?

### ISSUE THREAD

**Issue by ravener** [TorchedSammy/circleload#8]
The latest releases does not include a prebuilt binary and the `go install` command fails with:
```
~> go install github.com/TorchedSammy/Circleload@latest
go: downloading github.com/TorchedSammy/Circleload v0.3.1
go: github.com/TorchedSammy/Circleload@latest: github.com/TorchedSammy/Circleload@v0.3.1: parsing go.mod:
	module declares its path as: github.com/TorchedSammy/circleload
	        but was required as: github.com/TorchedSammy/Circleload
```
This seems to be fixed in the latest branch but it needs a release.

**Comment by ravener** [comment]
I got it built from source and can also say that the chimu mirror is broken but kitsu works

**Comment by sammy-ette** [comment]
in my personal use it seems like the entire program is broken, i'll do a rewrite or something eventually

**Comment by 10kmotorola** [comment]
@TorchedSammy please do! it would be awesome for this project to be able to be used again ^-^

**Comment by ravener** [comment]
I'd love to help contribute/maintain this if there's anything I can do, I've worked with Go before so it should be easy.

**Comment by sammy-ette** [comment]
I've made some code changes and all the mirrors work now (hopefully). To fix the original issue, just run `go install github.com/TorchedSammy/circleload@master`.

When I feel not lazy I'll work on some better readme and a changelog for a new release.
